version: '3.4'

services:
  catalogdb:
    container_name: ecommercemicroservices-catalogdb-1
    image: postgres:latest
    environment:
      - POSTGRES_DB=CatalogDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
    networks:
      - ecommercemicroservices_default

networks:
  ecommercemicroservices_default:
    external: true